language: generic

script:
  - bash ./deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "a99c6f361492"
    - COMMIT_AUTHOR_EMAIL: "cam@mcc.id.au"
notifications:
  email:
    on_success: never
    on_failure: always
